update dependencies.
Sifchain/sifnode pull request #1156
Opened 2021-04-20 15:02 UTC by khdegraaf

Updating dependencies to remove insecure libraries and packages.

2021-04-20 15:06 UTC, khdegraaf commented
I would like to either update these dependencies, or if there are any update issues, review the actual security alert and close it on a regular basis.

2021-04-20 15:11 UTC, khdegraaf commented
OK, looks like this does introduce some problems I need to either revert or fix.

2021-04-20 15:48 UTC, khdegraaf commented
OK, improved, but an issue still remains.

2021-05-14 17:46 UTC, banshee requested changes
Did we intend to stop checking in yarn.lock files completely?

2021-05-14 17:50 UTC, khdegraaf commented
Proof of concept I haven't finished.

2021-05-14 17:50 UTC, closed without merging