feature/testnet-deployments
Sifchain/sifnode pull request #138
Opened 2020-10-26 04:09 UTC by intl-man

Automated deployments for each PR.

2020-10-27 13:26 UTC, ilchebedelovski submitted a review, later dismissed
LGTM

2020-10-27 23:59 UTC, utx0 requested changes

2020-10-27 23:59 UTC, utx0 commented on build/rakelib/cluster.rake
> +    system("cd #{path(args)} && terraform destroy -auto-approve") or exit 1
I woundn't do `-auto-approve` on destroy...

2020-10-27 23:59 UTC, utx0 commented on build/terraform/template/aws/cluster.tf.tpl
> +            name = "sifchain-aws-feature-testnets"
Hey this should only be edited once the template has been scaffolded to `./live/*` Can we revert this.

2020-10-27 23:59 UTC, utx0 commented on build/terraform/template/aws/cluster.tf.tpl
> +    source                  = "github.com/sifchain/sifnode/build/terraform/providers/aws"
I would keep this relative as this means you have to have the repo cloned and you can also make edits locally and not change this unnecessarily

2020-10-27 23:59 UTC, utx0 commented on .github/workflows/feature.yml
> +          make CHAINNET=${{ steps.vars.outputs.sha_short }} BINARY=sifnoded build-image
We might need to handle this differently with the work I am in the process of doing so we can create a testnet build with testnet code ie fauct. Let talk when you are online to work this out.

2020-10-28 00:29 UTC, utx0 submitted a review, later dismissed

2020-10-28 00:30 UTC, utx0 commented on build/helm/sifnode/templates/sifnode-deployment.yaml
> +#        - name: {{ include "sifnode.fullname" . }}-ghcr
Clean up?

2020-10-28 00:30 UTC, utx0 commented on build/helm/sifnode/values.yaml
> +  tag: "develop"
is this correct?

2020-10-28 00:46 UTC, utx0 approved these changes

2020-10-28 00:46 UTC, merged