Testing/deployui
Sifchain/sifnode pull request #1404
Opened 2021-05-28 20:01 UTC by gboie

Updated requirements.txt with the latest. This is also design to get a Vercel URL.

2021-05-28 20:08 UTC, khdegraaf commented
But you are getting a Vercel UI link like I said.

2021-06-11 12:47 UTC, intl-man requested changes

2021-06-11 12:47 UTC, intl-man commented on cmd/ebrelayer/relayer/ethereum.go
> +	trailingBlocks      = 4
Why are you changing the relayer?

2021-06-11 12:47 UTC, intl-man commented on cmd/ebrelayer/txs/relayToEthereum.go
> +	transactionInterval = 3 * time.Second
I don't believe we should be changing this.

2021-06-11 12:47 UTC, intl-man commented on test/integration/FUTURES.txt
> +Ethereum
Can you please re-write it in markdown?

2021-06-11 12:47 UTC, intl-man commented on test/integration/ethereum_keys.json
> +{"addresses":{"0x627306090abab3a6e1400e9345bc60c78a8bef57":{"secretKey":{"type":"Buffer","data":[200,117,9,161,192,103,187,222,120,190,183,147,230,250,118,83,11,99,130,164,192,36,30,94,74,158,192,160
New line.

2021-09-02 16:16 UTC, closed without merging