ebrelayer meeting changes
Sifchain/sifnode pull request #1454
Opened 2021-06-07 19:20 UTC by banshee

2021-06-07 21:01 UTC, marshsif approved these changes
These have been ID'd as no longer in use, therefore they are being removed.

2021-06-08 02:07 UTC, juniuszhou approved these changes

2021-06-08 10:19 UTC, timlind requested changes

2021-06-08 10:19 UTC, timlind commented on proto/sifnode/ethbridge/v1/types.proto
>  message ProphecyClaim {
Prophecy Claim can also be removed here.

2021-06-08 10:59 UTC, timlind approved these changes

2021-06-08 14:55 UTC, merged