coding done.
Sifchain/sifnode pull request #1639
Opened 2021-07-23 01:02 UTC by juniuszhou

2021-07-26 16:42 UTC, ElliotFriedman requested changes

2021-07-26 16:42 UTC, ElliotFriedman commented on x/ethbridge/keeper/globalNonce_test.go
> +	assert.Equal(t, globalNonce, zeroGlobalNonce)
First global nonce should be 1, not 0.

2021-07-26 17:33 UTC, ElliotFriedman commented on x/ethbridge/keeper/globalNonce.go
> +		return uint64(0)
This should return 1, not 0.

2021-07-26 22:46 UTC, juniuszhou commented on x/ethbridge/keeper/globalNonce_test.go
> +	assert.Equal(t, globalNonce, zeroGlobalNonce)
will update it.

2021-07-29 23:37 UTC, ElliotFriedman approved these changes

2021-07-29 23:37 UTC, merged