Feature/coin metadata 1642
Sifchain/sifnode pull request #1669
Opened 2021-07-28 00:20 UTC by Brando753

2021-07-28 19:25 UTC, ElliotFriedman requested changes

2021-07-28 19:25 UTC, ElliotFriedman commented on cmd/ebrelayer/txs/parser.go
> +	witnessClaim.DenomHash = ethbridge.GetDenomHash(networkDescriptor, symbol, event.Decimals, event.Name, event.Symbol)
We decided to move away from this hashing denom model.

2021-07-28 19:25 UTC, ElliotFriedman commented on cmd/ebrelayer/txs/parser.go
> +	witnessClaim.DenomHash = ethbridge.GetDenomHash(networkDescriptor, symbol, event.Decimals, event.Name, event.Symbol)
We can remove this hash.

2021-07-28 19:25 UTC, ElliotFriedman commented on proto/sifnode/ethbridge/v1/types.proto
> +  string denom_hash = 13 [ (gogoproto.moretags) = "yaml:\"denom_hash\"" ];
Let's remove this.

2021-07-28 19:25 UTC, ElliotFriedman commented on x/ethbridge/types/claim.go
> +		DenomHash:             denomHash,
same comment as above on the denom hash.

2021-07-28 19:25 UTC, ElliotFriedman commented on x/ethbridge/types/claim.go
> +		claim.DenomHash,
Remove

2021-07-28 19:25 UTC, ElliotFriedman commented on x/ethbridge/types/claim.go
> +func GetDenomHash(
remove

2021-08-12 23:11 UTC, Brando753 commented
Code merged into Pull Request #1671

2021-08-12 23:11 UTC, closed without merging