added pagination for dispensation records
Sifchain/sifnode pull request #1699
Opened 2021-08-06 18:00 UTC by Jedi2002

2021-08-06 18:01 UTC, Jedi2002 commented
Unit tests are still pending

2021-08-06 18:17 UTC, timlind submitted a review, later dismissed

2021-09-02 10:29 UTC, timlind requested changes
Unit test updates?

2021-09-03 07:05 UTC, Jedi2002 commented
> Unit test updates?

Added

2021-09-25 16:45 UTC, iverc approved these changes

2022-03-30 03:39 UTC, closed without merging