Future/peggy2optimized native symbols
Sifchain/sifnode pull request #1751
Opened 2021-08-18 23:22 UTC by daniportugalgit

I branched off of future/peggy2optimized to do this because I don't think we can go back, it changed a lot of things.

This PR has everything from that branch, plus the ability to **set the native token's name and symbol during the initialization of BridgeBank**.

2021-08-30 21:49 UTC, ElliotFriedman requested changes

2021-08-30 21:49 UTC, ElliotFriedman commented on smart-contracts/contracts/CosmosBridge.sol
> +    ) private view returns(bool, uint256 pow) {
Let's remove the boolean being returned here and instead just revert if a false would have been returned.

2021-08-30 21:49 UTC, ElliotFriedman commented on smart-contracts/contracts/CosmosBridge.sol
> +        require(!dup, "DUP_SIGNER");
Let's remove this require statement and change `getSignedPowerAndFindDup` to only return a uint.

2021-09-01 22:59 UTC, ElliotFriedman commented
Let's pivot to a different architecture where instead of storing these things in storage and needing them in initialization of things, we just hardcode the native symbol to something like "evm_native".

2021-10-05 16:42 UTC, pandaring2you commented
hey @daniportugalgit - this task still valid?

2021-11-08 14:30 UTC, daniportugalgit commented
It actually is, Jordan. The change requested by Elliot was done somewhere,
but it probably stayed in a branch that was abandoned for some reason. I'll
bring it to my peggy2-blocklist branch.

On Tue, Oct 5, 2021 at 1:42 PM Jordan PM ***@***.***> wrote:

> hey @daniportugalgit <https://github.com/daniportugalgit> - this task
> still valid?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Sifchain/sifnode/pull/1751#issuecomment-934578122>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABH3DQ2JZA7A5V3ZOM6BTKLUFMTHVANCNFSM5CNA5QFQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-08 18:38 UTC, closed without merging

2021-11-08 18:38 UTC, daniportugalgit commented
We'll deal with this task in a different branch and PR