Prebuild ibc tokens
Sifchain/sifnode pull request #1809
Opened 2021-08-28 00:23 UTC by banshee

Don't merge this until we merge https://github.com/Sifchain/sifnode/pull/1808

2021-08-30 18:03 UTC, banshee commented on smart-contracts/src/ibcMatchingTokens.ts
> +    await token.transferOwnership(bridgeBank.address)
transferOwnership is no longer valid, this needs to be removed

2021-08-30 18:40 UTC, banshee commented
> Don't merge this until we merge #1808

That has been merged.

2021-09-08 18:06 UTC, ElliotFriedman requested changes

2021-09-08 18:06 UTC, ElliotFriedman commented on smart-contracts/hardhat.config.ts
> +// https://prod.liveshare.vsengsaas.visualstudio.com/join?84826512BD698D80121925FFF8F6A0D17A2A
Let's remove this.

2021-09-09 16:53 UTC, banshee commented on smart-contracts/hardhat.config.ts
> +// https://prod.liveshare.vsengsaas.visualstudio.com/join?84826512BD698D80121925FFF8F6A0D17A2A
Done

2021-09-09 20:04 UTC, ElliotFriedman approved these changes

2021-09-09 20:05 UTC, merged