Rename LimitUpdating.md to Whitelist_Update.md
Sifchain/sifnode pull request #1881
Opened 2021-09-16 00:49 UTC by musnit

2021-09-16 15:10 UTC, daniportugalgit requested changes
We should also update the file scripts/bulk_set_whitelist.ts, line 3:
From "Please read LimitUpdating.md for instructions" to "Please read Whitelist_Update.md for instructions"

2021-09-17 15:44 UTC, daniportugalgit approved these changes
LGTM

2021-09-17 17:35 UTC, ElliotFriedman approved these changes

2021-09-21 22:49 UTC, banshee approved these changes

2021-09-22 20:31 UTC, merged