Feature | add terra.json
Sifchain/sifnode pull request #1896
Opened 2021-09-18 13:40 UTC by iverc

2021-09-19 23:06 UTC, mccallofthewild approved these changes

2021-09-20 01:09 UTC, mccallofthewild requested changes
Adding all of the new ERC20's in addition to `cust`:
FRAX - Frax
FXS - Frax Share
ZCX - Unizen
DON - Don-key
METIS - Metis Token
KFT - Knit Finance
ZCN - 0chain
SAITO - SAITO
DFYN - DFYN Token
DNXC - DinoX Coin
ERN - @EthernityChain $ERN Token
POLS - PolkastarterToken
AXS - Axie Infinity Shard
MATIC - Matic Token
TOKE - Tokemak

2021-09-20 02:16 UTC, mccallofthewild approved these changes

2021-09-20 02:16 UTC, mccallofthewild submitted a review, later dismissed

2021-09-20 02:56 UTC, mccallofthewild submitted a review, later dismissed

2021-09-20 03:20 UTC, caseyturnerarrington approved these changes

2021-09-20 04:10 UTC, mccallofthewild approved these changes

2021-09-20 04:18 UTC, merged