[WIP][Frontend] Feature/Notifications
Sifchain/sifnode pull request #389
Opened 2020-12-14 21:20 UTC by 59023g

Notifications will display `error`, `success` and `information` messages to the user. For example, it'll notify them when they're connected to testnet, when their Metamask connection failed, and when there's no liquidity

- [ ] Notifications Store
- [ ] Notifcations Service
- [ ] Apply to certain events
- [ ] Notifications Tests
- [ ] Notifications UI Components

![image](https://user-images.githubusercontent.com/5235538/102136924-acdcec80-3e1f-11eb-8e02-3ecfde58c63c.png)

2020-12-18 04:41 UTC, ryardley requested changes
I think we want to set it up so that Notifications are only called from within usecases and it should look more like this:

![Untitled Diagram (3)](https://user-images.githubusercontent.com/1256409/102575475-4588aa80-4147-11eb-88c2-6d44bbcd2ece.png)

2020-12-18 04:43 UTC, ryardley commented on ui/core/src/api/utils/NotificationService.ts
> +type INotificationService = Boolean
Fire and forget we don't care about a return value here.

2020-12-18 16:42 UTC, 59023g commented
> I think we want to set it up so that Notifications are only called from within usecases and it should look more like this:
> 

I agree, that would be good, if possible and applicable.

Two issues: 
1) Action service calls do not have return values. They use `updateData()` and `effect()` so I'm unable to set notifications in `actions.connectToWallet()` for example. We'd have to refactor the app to make this happen. 
2) In certain instances, for example `getWeb3Provider()`, this happens upon invocation of app via `const etheriumState = api.EthereumService.getState();` not by an action specifically.

2020-12-18 16:44 UTC, 59023g commented on ui/core/src/api/EthereumService/index.ts
> +      notify({type: "success", message: "Connected to Metamask"})
See longer comment

2020-12-18 16:45 UTC, 59023g commented on ui/core/src/api/EthereumService/index.ts
> +          notify({type: "error", message: "Metamask not found.", detail: "Check if extension enabled for this URL."})
I moved this to `utils/getMetamaskProvider()`

2020-12-18 17:08 UTC, 59023g commented
> 1. Action service calls do not have return values. They use `updateData()` and `effect()` so I'm unable to set notifications in `actions.connectToWallet()` for example. We'd have to refactor the app to make this happen.

However, I realized I could remove `effect()`, invoke`connectToWallet()`, not have to refactor service return value, while still keeping the two states (ethService and store) in sync:

<img width="467" alt="Screen Shot 2020-12-18 at 11 04 57 AM" src="https://user-images.githubusercontent.com/5235538/102641153-3b53b580-4121-11eb-8f7c-1aa9738ac018.png">

2020-12-19 00:27 UTC, ryardley commented
> Action service calls do not have return values. They use updateData() and effect() so I'm unable to set notifications in actions.connectToWallet() for example. We'd have to refactor the app to make this happen.

It can probably be done like this:

```ts
let firstRun = true;

effect(() => {
  if (!firstRun) {
    if(etheriumState.connected)
      notify({type: "success", message: "Connected to Metamask"})
    else 
      notify({type: "info", message: "Disconnected"})
  }   
  store.wallet.eth.isConnected = etheriumState.connected;
});

effect(() => {
  // ...
})

firstRun = false;
```

However this highlights the problems with using refs to share state outside of vue land. Semantically this is much better:

```ts
api.EthereumService.onConnected(() => {
  store.wallet.eth.isConnected = true
  notify({type: "success", message: "Connected!"})
})

api.EthereumService.onDisconnected(() => {
  store.wallet.eth.isConnected = false
  notify({type: "success", message: "Disconnected!"})
})
```

2020-12-21 22:12 UTC, ryardley approved these changes

2020-12-21 22:46 UTC, merged