Update assets.ethereum.localnet.json with ropsten token addresses
Sifchain/sifnode pull request #517
Opened 2021-01-18 13:55 UTC by sauravtom

2021-01-19 01:15 UTC, ryardley commented
We should make a new file for ropsten: `ui/core/src/assets.ethereum.ropsten.json` and we can work out a way to integrate it later

2021-01-19 01:16 UTC, ryardley requested changes
We should make a new file for ropsten: ui/core/src/assets.ethereum.ropsten.json and we can work out a way to integrate it later

2021-01-19 01:17 UTC, ryardley requested changes

2021-01-19 01:17 UTC, ryardley commented on ui/core/src/assets.ethereum.localnet.json
> +      "network": "ropsten",
network should be "ethereum"

2021-04-01 00:18 UTC, banshee commented
This is obsolete and has been maintained in other ways since this PR

2021-04-01 00:18 UTC, closed without merging