Update assets.ethereum.mainnet.json with ethereum mainnet token addresses
Sifchain/sifnode pull request #518
Opened 2021-01-18 14:01 UTC by sauravtom

2021-01-19 01:10 UTC, ryardley submitted a review, later dismissed
Looks ok to me, although should `price_usd` be `priceUsd` ?

2021-01-20 05:30 UTC, ElliotFriedman requested changes

2021-01-20 05:30 UTC, ElliotFriedman commented on ui/core/src/assets.ethereum.mainnet.json
> +    "transferLimit": 5.003016819141942e+21
This needs to be turned into a string, and not have e+21 in it. Same goes for all other tokens that look like this.

2021-01-20 19:37 UTC, ElliotFriedman reviewed
Looks good to me. Please make sure to keep in touch with @jkbrooks in terms of what tokens we are actually going to have for mainnet as he will be setting the coins we will be using.

2021-01-29 01:01 UTC, ElliotFriedman submitted a review, later dismissed

2021-01-29 02:21 UTC, ElliotFriedman requested changes

2021-01-29 02:21 UTC, ElliotFriedman commented on ui/core/src/assets.ethereum.mainnet.json
> +      "address": "0xFd09Cf7cFffa9932e33668311C4777Cb9db3c9Be",
Why don't we use regular mana instead of wrapped mana? https://etherscan.io/token/0x0f5d2fb29fb7d3cfee444a200298f468908cc942

2021-01-29 03:21 UTC, ElliotFriedman commented on ui/core/src/assets.ethereum.mainnet.json
> +      "address": "0xFd09Cf7cFffa9932e33668311C4777Cb9db3c9Be",
Confirmed with Jazear that we will be using mana, not wrapped mana.

2021-01-29 03:36 UTC, ElliotFriedman approved these changes

2021-01-29 03:36 UTC, ElliotFriedman approved these changes

2021-01-29 15:33 UTC, merged