[ui] don't show peg buttons when asset amount is zero
Sifchain/sifnode pull request #695
Opened 2021-02-10 23:00 UTC by thomasdavis

2021-02-10 23:14 UTC, 59023g commented on ui/app/src/components/shared/AssetList.vue
> +        <slot v-if="Number(item.amount.toFixed(6)) > 0" :asset="item"></slot>
This may break app if Token has less than 6 decimals. Will you test it by changing a token in `assets.ethereum.ropsten.json` to have 5 decimals?

2021-02-11 00:45 UTC, 59023g requested changes
Please remove `toFixed(6)` - Can replace it with empty param, will then default to whatever `asset.decimal` value is. There's an issue where toFixed crashes app when param is greater than `asset.decimals`. Which only occurs for ETH assets

2021-02-11 00:58 UTC, thomasdavis commented
@59023g Yeah that works better, tested and pushed.

2021-02-11 01:01 UTC, 59023g approved these changes
Cool

2021-02-11 17:41 UTC, merged