Added config to update cloudflare dnslink records
Sifchain/sifnode pull request #701
Opened 2021-02-11 06:00 UTC by utx0

2021-02-11 06:59 UTC, brentmcd approved these changes

2021-02-11 06:59 UTC, brentmcd approved these changes

2021-02-11 07:00 UTC, intl-man submitted a review, later dismissed

2021-02-11 16:43 UTC, 59023g requested changes
Nice. Check the `$GITHUB_BASE_REF == 'master'` issue.

2021-02-11 16:43 UTC, 59023g commented on .github/workflows/pinata-build-deploy-ui.yml
>            if [[ $GITHUB_BASE_REF == 'master' ]]; then
I found an issue with this line. Looks like should be `refs/heads/master` not `master`.  See: https://github.com/Sifchain/sifnode/runs/1876970414?check_suite_focus=true#step:4:16

2021-02-17 08:12 UTC, brentmcd approved these changes

2021-02-17 08:13 UTC, intl-man approved these changes

2021-02-17 08:17 UTC, merged