[ui] core/config: ceth decimals
Sifchain/sifnode pull request #728
Opened 2021-02-13 16:32 UTC by 59023g

Were missing. Prevents keplr from connecting

2021-02-13 17:30 UTC, ElliotFriedman approved these changes

2021-02-13 20:07 UTC, ElliotFriedman approved these changes

2021-02-13 20:17 UTC, ElliotFriedman requested changes
I don't think this change is needed.

2021-02-15 00:35 UTC, 59023g commented
Closing. Should target `develop`

2021-02-15 00:36 UTC, closed without merging