[ui] fix for making back button work on pooling in different states
Sifchain/sifnode pull request #782
Opened 2021-02-19 02:22 UTC by thomasdavis

2021-02-19 17:36 UTC, 59023g approved these changes

2021-02-23 00:18 UTC, ryardley submitted a review, later dismissed
I believe this also fixes a bug where the whole page was disappearing when you hit back and dont have funds in a pool.

2021-02-23 00:46 UTC, ryardley commented on ui/app/src/views/CreatePoolPage.vue
> +        if (fromSymbol.value && connected && Number(aPerBRatioMessage.value) > 0 &&
Just had a thought here it might be better to try and just use `router.back()`

2021-02-27 04:32 UTC, 59023g requested changes
I just tested this again. Doesn't work: `/pool/cctoken -> /pool/add-liquidity/cctoken "click back" -> /pool`

However, I tried @ryardley 's suggestion and all the cases *I know* worked. I know there's a case I'm missing.

2021-03-02 03:18 UTC, 59023g approved these changes
Ship it!!

2021-03-02 11:39 UTC, merged