[UI] Fix pool stats
Sifchain/sifnode pull request #860
Opened 2021-02-26 14:36 UTC by iverc

2021-02-26 20:51 UTC, 59023g approved these changes

2021-02-27 04:40 UTC, 59023g requested changes
<img width="627" alt="Screen Shot 2021-02-26 at 8 39 44 PM" src="https://user-images.githubusercontent.com/5235538/109375599-d0d29a80-7872-11eb-97a8-43d738594f2f.png">
The tooltip margins look off here

2021-02-27 07:03 UTC, iverc commented
@59023g no changes to margins were made and this is actually just a rollback of the test label values. Fixing margins, but if we need to deploy  asap - I suggest merging it in as it does not make it worse compared to the existing version.

2021-03-01 18:52 UTC, 59023g approved these changes

2021-03-02 18:42 UTC, merged