added new AnteHandler to make tx free for request faucet
Sifchain/sifnode pull request #934
Opened 2021-03-10 19:01 UTC by Jedi2002

2021-03-11 05:56 UTC, khdegraaf requested changes

2021-03-11 05:56 UTC, khdegraaf commented on app/app.go
> +			faucet.NewRemoveFacuetFeeDecorator(),
NewRemoveFacuetFeeDecorator -> NewRemoveFaucetFeeDecorator

spelling...

2021-03-11 05:56 UTC, khdegraaf commented on x/faucet/types/ante.go
> +func NewRemoveFacuetFeeDecorator() RemoveFaucetFeeDecorator {
NewRemoveFacuetFeeDecorator -> NewRemoveFaucetFeeDecorator

spelling...

2021-03-21 20:07 UTC, Jedi2002 commented
Closing this pr , THe other PR for TX-FEE 2.0 has a better implementation for this

2021-03-21 20:07 UTC, closed without merging