Update testnet.md
Sifchain/sifnode pull request #987
Opened 2021-03-22 14:00 UTC by lufa23

Getting the same question quite often, i think it can help to be more clear on the faucet

2021-03-24 07:50 UTC, intl-man requested changes
@lufa23 Nice one. Thanks for this. I'd probably just change that sentence to read:

```
If using the testnet, please request funds via our [faucet discord channel](https://discord.com/invite/geqyCWSU5K).
```

2021-04-27 22:27 UTC, lufa23 commented
done

2021-04-27 22:32 UTC, lufa23 reviewed
ok

2021-05-05 12:12 UTC, intl-man approved these changes

2021-05-14 05:34 UTC, merged